use crate::services::themers::{ThemeContext, Themer};
use crate::utils::paths::Paths;
use std::fmt::Write;
use std::fs;

pub struct HyprThemer;

impl Themer for HyprThemer {
    fn apply(&self, context: &ThemeContext<'_>) -> Result<(), String> {
        let style_variables_file_path =
            Paths::user_home()?.join(".config/hypr/style-variables.conf");

        let theme_variables_css_file_path = context.theme.get_theme_variables_css_file_path();

        let mut output = String::new();

        writeln!(
            output,
            "# Autogenerated from {}",
            theme_variables_css_file_path.display()
        )
        .map_err(|e| format!("Could not write line. {e}"))?;

        for (name, value) in &context.variables {
            writeln!(output, "${name} = {value}")
                .map_err(|e| format!("Could not write line. {e}"))?;
        }

        fs::create_dir_all(style_variables_file_path.parent().unwrap()).map_err(|e| {
            format!(
                "Could not create parent directories for {}. {e}",
                style_variables_file_path.display()
            )
        })?;

        fs::write(&style_variables_file_path, output).map_err(|e| {
            format!(
                "Could not write to {}. {e}",
                style_variables_file_path.display()
            )
        })?;

        Ok(())
    }
}
