use crate::models::hex_color::HexColor;
use crate::services::themers::{ThemeContext, Themer};
use crate::utils::paths::Paths;
use regex::Regex;
use std::fmt::Write;
use std::fs;
use std::process::{Command, Stdio};

pub struct KittyThemer;

impl Themer for KittyThemer {
    fn apply(&self, context: &ThemeContext<'_>) -> Result<(), String> {
        let home_path = Paths::user_home()?;
        let kitty_theme_conf_file_path = &home_path.join(".config/kitty/theme.conf");
        let theme_template_file_path = &home_path.join(".config/kitty/theme-template.conf");

        let kitty_theme_template = fs::read_to_string(theme_template_file_path).map_err(|e| {
            format!(
                "Could not read contents of {}: {}",
                theme_template_file_path.display(),
                e
            )
        })?;

        let mut output = String::new();

        writeln!(
            output,
            "# Autogenerated from {}",
            context.theme.get_theme_variables_css_file_path().display()
        )
        .map_err(|e| format!("Could not write line. {e}"))?;

        let replacement_variable_regex = Regex::new(r"__(:?.*)__").unwrap();

        for line in kitty_theme_template.lines() {
            let Some(captures) = replacement_variable_regex.captures(line) else {
                writeln!(output, "{line}").map_err(|e| format!("Could not write line. {e}"))?;
                continue;
            };

            if captures.len() != 2 {
                writeln!(output, "{line}").map_err(|e| format!("Could not write line. {e}"))?;
                continue;
            }

            let replacement_variable = captures[0].to_string();
            let variable_name = captures[1].to_string();

            let Some(variable) = context.variables.iter().find(|v| v.0 == variable_name) else {
                writeln!(output, "{line}").map_err(|e| format!("Could not write line. {e}"))?;
                continue;
            };

            let variable_value = &variable.1;
            let hex_color: HexColor = variable_value.try_into()?;
            let hex_string: String = hex_color.into();
            let new_line = line.replace(&replacement_variable, &hex_string);

            writeln!(output, "{new_line}").map_err(|e| format!("Could not write line. {e}"))?;
        }

        fs::write(kitty_theme_conf_file_path, output).map_err(|e| {
            format!(
                "Could not write {}. {e}",
                kitty_theme_conf_file_path.display()
            )
        })?;

        Command::new("kitty")
            .arg("@")
            .arg("--no-response")
            .arg("load-config")
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .map_err(|e| format!("Could not execute 'load-config' command for Kitty. {e}"))?;

        Ok(())
    }
}
